const eventConstants = {
  EVENT_LIST_REQUEST : "EVENT_LIST_REQUEST",
  EVENT_LIST_SUCCESS : "EVENT_LIST_SUCCESS",
  EVENT_LIST_FAIL    : "EVENT_LIST_FAIL",
  EVENT_DETAILS_SUCCESS : "EVENT_DETAILS_SUCCESS",
  EVENT_DETAILS_REQUEST : "EVENT_DETAILS_REQUEST",
  EVENT_DETAILS_FAIL    : "EVENT_DETAILS_FAIL"
}

module.exports = eventConstants;