 const productConstants = {
    PRODUCT_LIST_REQUEST : "PRODUCT_LIST_REQUEST",
    PRODUCT_LIST_SUCCESS : "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAIL    : "PRODUCT_LIST_FAIL",

    PRODUCT_SAVE_REQUEST : "PRODUCT_SAVE_REQUEST",
    PRODUCT_SAVE_SUCCESS : "PRODUCT_SAVE_SUCCESS",
    PRODUCT_SAVE_FAIL    : "PRODUCT_SAVE_FAIL",

    PRODUCT_EDIT_REQUEST : "PRODUCT_EDIT_REQUEST",
    PRODUCT_EDIT_SUCCESS : "PRODUCT_EDIT_SUCCESS",
    PRODUCT_EDIT_FAIL    : "PRODUCT_EDIT_FAIL",

    PRODUCT_DELETE_REQUEST : "PRODUCT_DELETE_REQUEST",
    PRODUCT_DELETE_SUCCESS : "PRODUCT_DELETE_SUCCESS",
    PRODUCT_DELETE_FAIL    : "PRODUCT_DELETE_FAIL",

    PRODUCT_DETAILS_SUCCESS : "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_REQUEST : "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_FAIL    : "PRODUCT_DETAILS_FAIL",

    DELETE_IMAGES_REQUEST : "DELETE_IMAGES_REQUEST",
    DELETE_IMAGES_SUCCESS : "DELETE_IMAGES_SUCCESS",
    DELETE_IMAGES_FAIL    : "DELETE_IMAGES_FAIL",

    UPLOAD_IMAGES_REQUEST : "UPLOAD_IMAGES_REQUEST",
    UPLOAD_IMAGES_SUCCESS : "UPLOAD_IMAGES_SUCCESS",
    UPLOAD_IMAGES_FAIL    : "UPLOAD_IMAGES_FAIL"
}

module.exports = productConstants;