const userConstants = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL   : "USER_LOGIN_FAIL",
  
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL   : "USER_REGISTER_FAIL",

  USER_EDIT_REQUEST: "USER_EDIT_REQUEST",
  USER_EDIT_SUCCESS: "USER_EDIT_SUCCESS",
  USER_EDIT_FAIL   : "USER_EDIT_FAIL",

  USER_DELETE_REQUEST: "USER_DELETE_REQUEST",
  USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  USER_DELETE_FAIL   : "USER_DELETE_FAIL",

  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAIL   : "USER_DETAILS_FAIL",
}

module.exports = userConstants;